[versions]
agp = "8.9.0"
androidActivation = "1.6.7"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
preference = "1.2.1"
firebaseFirestore = "25.1.2"
navigationRuntimeAndroid = "2.9.0-alpha09"

[libraries]
android-activation = { module = "com.sun.mail:android-activation", version.ref = "androidActivation" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "androidActivation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

